import { generateAccessToken, paypal } from "../lib/paypal";


// Test to generate access token from paypal. 
// If the string is empty, null, or not a string, it means something went wrong (e.g., authentication failed, 
// environment variables are missing, or the API is down). This check ensures the integration is working and 
// you have the credentials needed for further PayPal API calls.
test('generates a token from paypal', async () => {
    const tokenResponse = await generateAccessToken();
    console.log(tokenResponse);
    console.log(tokenResponse.length);
    expect(typeof tokenResponse).toBe('string');
    expect(tokenResponse.length).toBeGreaterThan(0);
});


// Test to create a PayPal order. It checks if it returns an object with an id property/status property and 
// created status to confirm that the PayPal order was successfully created. The id is a unique identifier for the order, 
// generated by PayPal. If the response does not include an id, it means the order creation failed or the API response is 
// not as expected. This check ensures the integration is working and you can reference or capture the order in later steps.
test('creates a PaylPal order', async () => {
    const token = await generateAccessToken();
    const price = 10.0;
    const orderResponse = await paypal.createOrder(price);
    console.log(orderResponse);

    expect(orderResponse).toHaveProperty('id');
    expect(orderResponse).toHaveProperty('status');
    expect(orderResponse.status).toBe('CREATED');
});


// Test to capture payment
test('simulate capturing payment from order', async () => {
    const orderId = 100;
    // Uses Jest’s spyOn function to create a mock (spy) for the capturePayment method on the paypal object. 
    // This allows you to intercept and control calls to paypal.capturePayment during the test.
    // .mockResolvedValue({ status: 'COMPLETED }). This Configures the mock so that whenever paypal.capturePayment 
    // is called, it returns a Promise that resolves to the object { status: 'COMPLETED' } (simulating a 
    // successful payment capture).
    const mockCapturePayment = jest.spyOn(paypal, 'capturePayment').mockResolvedValue({
        status: 'COMPLETED',
    });
    const captureResponse = await paypal.capturePayment(orderId);
    expect(captureResponse).toHaveProperty('status', 'COMPLETED');

    mockCapturePayment.mockRestore();
})


// Line 41 tells Jest: “Whenever paypal.capturePayment is called in this test, don’t run the real code—just return 
// a resolved Promise with { status: 'COMPLETED' } instead.” This is useful for testing code that depends on 
// capturePayment without making real API calls.